/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_LOGPROTO_LOGPROTO_PB_H_INCLUDED
#define PB_LOGPROTO_LOGPROTO_PB_H_INCLUDED
#include <pb.h>
#include "timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _logproto_PushRequest { 
    pb_callback_t streams; 
} logproto_PushRequest;

typedef struct _logproto_PushResponse { 
    char dummy_field;
} logproto_PushResponse;

typedef struct _logproto_StreamAdapter { 
    pb_callback_t labels; 
    pb_callback_t entries; 
} logproto_StreamAdapter;

typedef struct _logproto_EntryAdapter { 
    bool has_timestamp;
    google_protobuf_Timestamp timestamp; 
    pb_callback_t line; 
} logproto_EntryAdapter;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define logproto_PushRequest_init_default        {{{NULL}, NULL}}
#define logproto_PushResponse_init_default       {0}
#define logproto_StreamAdapter_init_default      {{{NULL}, NULL}, {{NULL}, NULL}}
#define logproto_EntryAdapter_init_default       {false, google_protobuf_Timestamp_init_default, {{NULL}, NULL}}
#define logproto_PushRequest_init_zero           {{{NULL}, NULL}}
#define logproto_PushResponse_init_zero          {0}
#define logproto_StreamAdapter_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}}
#define logproto_EntryAdapter_init_zero          {false, google_protobuf_Timestamp_init_zero, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define logproto_PushRequest_streams_tag         1
#define logproto_StreamAdapter_labels_tag        1
#define logproto_StreamAdapter_entries_tag       2
#define logproto_EntryAdapter_timestamp_tag      1
#define logproto_EntryAdapter_line_tag           2

/* Struct field encoding specification for nanopb */
#define logproto_PushRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  streams,           1)
#define logproto_PushRequest_CALLBACK pb_default_field_callback
#define logproto_PushRequest_DEFAULT NULL
#define logproto_PushRequest_streams_MSGTYPE logproto_StreamAdapter

#define logproto_PushResponse_FIELDLIST(X, a) \

#define logproto_PushResponse_CALLBACK NULL
#define logproto_PushResponse_DEFAULT NULL

#define logproto_StreamAdapter_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   labels,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           2)
#define logproto_StreamAdapter_CALLBACK pb_default_field_callback
#define logproto_StreamAdapter_DEFAULT NULL
#define logproto_StreamAdapter_entries_MSGTYPE logproto_EntryAdapter

#define logproto_EntryAdapter_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         1) \
X(a, CALLBACK, SINGULAR, STRING,   line,              2)
#define logproto_EntryAdapter_CALLBACK pb_default_field_callback
#define logproto_EntryAdapter_DEFAULT NULL
#define logproto_EntryAdapter_timestamp_MSGTYPE google_protobuf_Timestamp

extern const pb_msgdesc_t logproto_PushRequest_msg;
extern const pb_msgdesc_t logproto_PushResponse_msg;
extern const pb_msgdesc_t logproto_StreamAdapter_msg;
extern const pb_msgdesc_t logproto_EntryAdapter_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define logproto_PushRequest_fields &logproto_PushRequest_msg
#define logproto_PushResponse_fields &logproto_PushResponse_msg
#define logproto_StreamAdapter_fields &logproto_StreamAdapter_msg
#define logproto_EntryAdapter_fields &logproto_EntryAdapter_msg

/* Maximum encoded size of messages (where known) */
/* logproto_PushRequest_size depends on runtime parameters */
/* logproto_StreamAdapter_size depends on runtime parameters */
/* logproto_EntryAdapter_size depends on runtime parameters */
#define logproto_PushResponse_size               0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
