/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "logproto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(logproto_PushRequest, logproto_PushRequest, AUTO)


PB_BIND(logproto_PushResponse, logproto_PushResponse, AUTO)


PB_BIND(logproto_StreamAdapter, logproto_StreamAdapter, AUTO)


PB_BIND(logproto_EntryAdapter, logproto_EntryAdapter, AUTO)



